Milestone 2
milosvukadinovic/Calculator-React pull request #3
Opened 2019-09-13 14:30 UTC by milosvukadinovic

2019-09-16 10:51 UTC, SunnyAsar requested changes
# Hello @milosvukadinovic  👋 
Nice work setting up your project neatly, just missed out on a few validation of the propType and setting default values, i have commented below what needs change.
#### Note
- There is a milestone for styling but setting it up now to at least be a grid wont hurt
- Clean up your `ReadMe` and make it descriptive of the project.
- You have some linting issues, please fix them and setup a [linter](https://github.com/microverseinc/linters-config/tree/master/react-redux) for your repository too.

**Please make the changes and request another review when you are done**
Good job so far

2019-09-16 10:51 UTC, SunnyAsar commented on src/Components/Display.js
> +    <h1>Display</h1>
display needs to accept as props the result of the calculation

2019-09-16 10:51 UTC, SunnyAsar commented on src/Components/Display.js
> +
also lets add a default prop value for when there is no result set yet and let have propTypes as well.

2019-09-16 10:51 UTC, SunnyAsar commented on src/Components/Button.js
> +);
let's add propType here too to validate that prop.name is a string.

2019-09-18 11:15 UTC, merged

2019-09-30 16:36 UTC, BalintMendli reviewed
Hi @milosvukadinovic ,

I see that you have this milestone left over.

As requirements all met I mark it approved now.

👍